name: Node.js CI

stages:
  - build
  - deploy

only:
  - main

build-job:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - .next/

build-image-docker:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
